#ifndef DEFINATION_H
#define DEFINATION_H
#define SIGNAL_LEFT_PIN 4
#define SIGNAL_RIGHT_PIN 5
#define HEADLIGHT_PIN 6
#define BACKLIGHT_PIN 8
#define BACK_HEADLIGHT_PIN 9

#define LONG_HEADLIGHT_VALUE 100
#define SHORT_HEADLIGHT_VALUE 20
#endif